package output

import (
	"fmt"
	"strings"
)

// translationGuide is the header prepended to translation templates.
const translationGuide = `<!-- ============================================================
     TRANSLATION TEMPLATE
     ============================================================

     This file is a translation template generated by steel-etl.

     HOW TO TRANSLATE:
     1. Translate all human-readable text (headings, paragraphs,
        table cells, flavor text, effect descriptions).
     2. DO NOT translate or modify:
        - HTML comment annotations: <!-- @type: ... -->
        - YAML frontmatter between --- markers
        - Markdown formatting (**, ##, |, -, etc.)
        - Keywords in annotations (@type, @id, @cost, etc.)
        - SCC codes (e.g., scc:mcdm.heroes.v1/...)
        - Proper nouns that are game mechanics (ability names,
          class names) — unless your localization team has
          agreed-upon translations for them.
     3. Preserve the exact structure: same number of headings,
        same table row counts, same list item counts.
     4. Keep annotations in the same position relative to headings.

     AFTER TRANSLATING:
     - Save this file to: input/i18n/{locale}/%s
     - Run: steel-etl gen --locale {locale}
     - Verify output in: {base_dir}/{locale}/md/

     ============================================================ -->

`

// TranslationTemplate returns the annotated markdown with a translation guide
// header prepended. Annotations are preserved so the pipeline can process the
// translated file identically to the English source.
func TranslationTemplate(input string, filename string) string {
	header := fmt.Sprintf(translationGuide, filename)

	// If the input starts with frontmatter, insert the guide after it
	// so the YAML frontmatter remains the first thing in the file.
	if strings.HasPrefix(input, "---\n") {
		endIdx := strings.Index(input[4:], "\n---\n")
		if endIdx >= 0 {
			fmEnd := endIdx + 4 + 4 + 1 // skip past closing ---\n
			return input[:fmEnd] + "\n" + header + input[fmEnd:]
		}
	}

	return header + input
}
